language: android
android:
  components:
  - build-tools-28.0.3
  - android-28
before_install:
- openssl aes-256-cbc -K $encrypted_0ff029239134_key -iv $encrypted_0ff029239134_iv
  -in google-services.json.enc -out google-services.json -d
