language: android
sudo: false
android:
  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  components:
  - tools
  - platform-tools
  # Build Tools used for project
  - build-tools-28.0.3
  # Compile Sdk Version
  - android-28
  #  Emulator version
  # android-21
  # Additional components
  - extra-google-google_play_services
  - extra-google-m2repository
  # sys-img-armeabi-v7a-google_apis-21
before_install:
#  google-json encrypted for firebase
- openssl aes-256-cbc -K $encrypted_0ff029239134_key -iv $encrypted_0ff029239134_iv -in google-services.json.enc -out app/google-services.json -d
script:
- ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
