language: android
android:
  components:
  # Build Tools used for project
  - build-tools-28.0.3
  # Compile Sdk Version
  - android-28
  # Additional components
  - extra-google-google_play_services
  - extra-google-m2repository
  - sys-img-armeabi-v7a-google_apis-21
before_install:
#  google-json encrypted for firebase
- openssl aes-256-cbc -K $encrypted_0ff029239134_key -iv $encrypted_0ff029239134_iv -in google-services.json.enc -out app/google-services.json -d
env:
  global:
  # install timeout in minutes (2 minutes by default)
  - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
before_script:
- echo no | android create avd --force -n test -t android-21 --abi sys-img-armeabi-v7a-google-apis
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &